// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateCompanyValidationError
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_an_existing_customer_company_with_an_empty_company" +
        "_name_returns_a_bad_request_with_validation_errors.")]
    public partial class UpdateCustomerCompanyValidationFeature : object, global::Xunit.IClassFixture<UpdateCustomerCompanyValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_an_existing_customer_company_with_an_empty_company" +
                    "_name_returns_a_bad_request_with_validation_errors."};

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateCompanyValidationError", "Update customer company validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "UpdateCompanyValidationError.feature"
#line hidden

        public UpdateCustomerCompanyValidationFeature(UpdateCustomerCompanyValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateCompanyValidationError/UpdateCompanyValidationError.featu" +
                    "re.ndjson", 3);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Update existing customer company with empty company name returns bad request")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer company validation")]
        [global::Xunit.TraitAttribute("Description", "Update existing customer company with empty company name returns bad request")]
        public async global::System.Threading.Tasks.Task UpdateExistingCustomerCompanyWithEmptyCompanyNameReturnsBadRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update existing customer company with empty company name returns bad request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] { "Field", "Value" });
                table1.AddRow(new string[] { "ExternalId", "customer-update-company-validation" });
                table1.AddRow(new string[] { "Individual.FirstName", "Company" });
                table1.AddRow(new string[] { "Individual.LastName", "Validation" });
                table1.AddRow(new string[] { "Individual.Email", "company.validation@example.com" });
                table1.AddRow(new string[] { "Individual.Phone", "123456789" });
                table1.AddRow(new string[] { "Individual.BillingAddress.PostalCode", "00-001" });
                table1.AddRow(new string[] { "Individual.BillingAddress.City", "Warsaw" });
                table1.AddRow(new string[] { "Individual.BillingAddress.Street", "Marszalkowska" });
                table1.AddRow(new string[] { "Individual.BillingAddress.BuildingNumber", "10" });
                table1.AddRow(new string[] { "Individual.BillingAddress.ApartmentNumber", "5" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.PostalCode", "30-002" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.City", "Krakow" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.Street", "Dluga" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.BuildingNumber", "12" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.ApartmentNumber", "7" });
                table1.AddRow(new string[] { "Company.TaxId", "1234567890" });
                table1.AddRow(new string[] { "Company.CompanyName", "Example Validation Company" });
                table1.AddRow(new string[] { "Company.BillingAddress.PostalCode", "00-950" });
                table1.AddRow(new string[] { "Company.BillingAddress.City", "Warsaw" });
                table1.AddRow(new string[] { "Company.BillingAddress.Street", "Prosta" });
                table1.AddRow(new string[] { "Company.BillingAddress.BuildingNumber", "20" });
                table1.AddRow(new string[] { "Company.BillingAddress.ApartmentNumber", "15" });
                table1.AddRow(new string[] { "Company.ShippingAddress.PostalCode", "80-001" });
                table1.AddRow(new string[] { "Company.ShippingAddress.City", "Gdansk" });
                table1.AddRow(new string[] { "Company.ShippingAddress.Street", "Portowa" });
                table1.AddRow(new string[] { "Company.ShippingAddress.BuildingNumber", "4A" });
                table1.AddRow(new string[] { "Company.ShippingAddress.ApartmentNumber", "2" });
#line 5
    await testRunner.GivenAsync("a customer with company exists for update company validation request", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] { "Field", "Value" });
                table2.AddRow(new string[] { "Company.TaxId", "9876543210" });
                table2.AddRow(new string[] { "Company.CompanyName", "" });
                table2.AddRow(new string[] { "Company.BillingAddress.PostalCode", "01-234" });
                table2.AddRow(new string[] { "Company.BillingAddress.City", "Poznan" });
                table2.AddRow(new string[] { "Company.BillingAddress.Street", "Nowa" });
                table2.AddRow(new string[] { "Company.BillingAddress.BuildingNumber", "30" });
                table2.AddRow(new string[] { "Company.BillingAddress.ApartmentNumber", "8" });
                table2.AddRow(new string[] { "Company.ShippingAddress.PostalCode", "70-001" });
                table2.AddRow(new string[] { "Company.ShippingAddress.City", "Szczecin" });
                table2.AddRow(new string[] { "Company.ShippingAddress.Street", "Morska" });
                table2.AddRow(new string[] { "Company.ShippingAddress.BuildingNumber", "9B" });
                table2.AddRow(new string[] { "Company.ShippingAddress.ApartmentNumber", "11" });
#line 33
    await testRunner.AndAsync("I have an invalid update company request", ((string)(null)), table2, "And ");
#line hidden
#line 46
    await testRunner.WhenAsync("I submit the update company request for validation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] { "Field", "Value" });
                table3.AddRow(new string[] { "StatusCode", "400" });
                table3.AddRow(new string[] { "Message", "Company Name cannot be empty or white space." });
                table3.AddRow(new string[] { "Name", "CompanyDataCompanyNameValidationRule" });
                table3.AddRow(new string[] { "Entity", "CompanyData" });
#line 47
    await testRunner.ThenAsync("updating the company fails with a validation error", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerCompanyValidationFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerCompanyValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
