// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateCompanyValidationError
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_existing_customer_company_data_with_invalid_u" +
        "pdate_company_contract_values_returns_a_bad_request_with_validation_errors.")]
    public partial class UpdateCustomerCompanyDataValidationFeature : object, global::Xunit.IClassFixture<UpdateCustomerCompanyDataValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_existing_customer_company_data_with_invalid_u" +
                    "pdate_company_contract_values_returns_a_bad_request_with_validation_errors."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateCompanyValidationError", "Update customer company data validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateCompanyValidationError.feature"
#line hidden
        
        public UpdateCustomerCompanyDataValidationFeature(UpdateCustomerCompanyDataValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateCompanyValidationError/UpdateCompanyValidationError.feat" +
                    "ure.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update existing customer company data with invalid tax id and company name return" +
            "s bad request")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer company data validation")]
        [global::Xunit.TraitAttribute("Description", "Update existing customer company data with invalid tax id and company name return" +
            "s bad request")]
        public async global::System.Threading.Tasks.Task UpdateExistingCustomerCompanyDataWithInvalidTaxIdAndCompanyNameReturnsBadRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update existing customer company data with invalid tax id and company name return" +
                    "s bad request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table67.AddRow(new string[] {
                            "ExternalId",
                            "customer-update-company-validation-123"});
                table67.AddRow(new string[] {
                            "FirstName",
                            "Existing"});
                table67.AddRow(new string[] {
                            "LastName",
                            "CompanyOwner"});
                table67.AddRow(new string[] {
                            "Email",
                            "update.company.validation@db.com"});
                table67.AddRow(new string[] {
                            "Phone",
                            "111222333"});
                table67.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-001"});
                table67.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table67.AddRow(new string[] {
                            "BillingStreet",
                            "Main Street"});
                table67.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "10"});
                table67.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "20"});
                table67.AddRow(new string[] {
                            "ShippingPostalCode",
                            "00-002"});
                table67.AddRow(new string[] {
                            "ShippingCity",
                            "Krakow"});
                table67.AddRow(new string[] {
                            "ShippingStreet",
                            "Shipping Street"});
                table67.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "15"});
                table67.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "25"});
                table67.AddRow(new string[] {
                            "CompanyTaxId",
                            "1234567890"});
                table67.AddRow(new string[] {
                            "CompanyName",
                            "Existing Company Sp. z o.o."});
                table67.AddRow(new string[] {
                            "CompanyBillingPostalCode",
                            "10-100"});
                table67.AddRow(new string[] {
                            "CompanyBillingCity",
                            "Poznan"});
                table67.AddRow(new string[] {
                            "CompanyBillingStreet",
                            "Company Billing Street"});
                table67.AddRow(new string[] {
                            "CompanyBillingBuildingNumber",
                            "5"});
                table67.AddRow(new string[] {
                            "CompanyBillingApartmentNumber",
                            "11"});
                table67.AddRow(new string[] {
                            "CompanyShippingPostalCode",
                            "20-200"});
                table67.AddRow(new string[] {
                            "CompanyShippingCity",
                            "Wroclaw"});
                table67.AddRow(new string[] {
                            "CompanyShippingStreet",
                            "Company Shipping Street"});
                table67.AddRow(new string[] {
                            "CompanyShippingBuildingNumber",
                            "7B"});
                table67.AddRow(new string[] {
                            "CompanyShippingApartmentNumber",
                            "14"});
#line 5
    await testRunner.GivenAsync("a customer with a company exists for update company validation request", ((string)(null)), table67, "Given ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table68.AddRow(new string[] {
                            "TaxId",
                            "invalid-tax-id"});
                table68.AddRow(new string[] {
                            "CompanyName",
                            ""});
                table68.AddRow(new string[] {
                            "BillingPostalCode",
                            "30-300"});
                table68.AddRow(new string[] {
                            "BillingCity",
                            "Gdansk"});
                table68.AddRow(new string[] {
                            "BillingStreet",
                            "Updated Billing Street"});
                table68.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "22"});
                table68.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "3"});
                table68.AddRow(new string[] {
                            "ShippingPostalCode",
                            "40-400"});
                table68.AddRow(new string[] {
                            "ShippingCity",
                            "Lodz"});
                table68.AddRow(new string[] {
                            "ShippingStreet",
                            "Updated Shipping Street"});
                table68.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "44"});
                table68.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "8"});
#line 34
    await testRunner.AndAsync("I have an invalid update company request", ((string)(null)), table68, "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("I submit the update company request for validation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table69.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table69.AddRow(new string[] {
                            "TaxIdMessage",
                            "Tax Id must be a valid Polish NIP containing exactly 10 digits."});
                table69.AddRow(new string[] {
                            "TaxIdName",
                            "CompanyDataTaxIdValidationRule"});
                table69.AddRow(new string[] {
                            "TaxIdEntity",
                            "CompanyData"});
                table69.AddRow(new string[] {
                            "CompanyNameMessage",
                            "Company Name cannot be empty or white space."});
                table69.AddRow(new string[] {
                            "CompanyNameName",
                            "CompanyDataCompanyNameValidationRule"});
                table69.AddRow(new string[] {
                            "CompanyNameEntity",
                            "CompanyData"});
#line 49
    await testRunner.ThenAsync("updating the company data fails with validation errors", ((string)(null)), table69, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerCompanyDataValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerCompanyDataValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
