version: '3.8'

services:
  # 1. Your .NET Web API Service  
  ecommercestoreusers.api:
    image: ${DOCKER_REGISTRY-}ecommercestoreusersapi
    build:
      context: .
      dockerfile: src/ECommerceStoreUsers.API/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MongoDbSettings__ConnectionString=c
    ports:
      - "8080:8080" 
      - "8081:8081" 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - compose-mongodb

  # 2. The MongoDB 8 Service (Renamed service to compose-mongodb)
  compose-mongodb:
    image: mongo:8
    container_name: local-mongodb
    ports:
      - "27018:27017" # Exposed to your windows host on port 27018
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: