// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Admins.UpdateAdminNotFound
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_a_missing_admin_profile_by_admin_id_return" +
        "s_a_not_found_problem_details_response.")]
    public partial class UpdateAdminProfileNotFoundFeature : object, global::Xunit.IClassFixture<UpdateAdminProfileNotFoundFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_a_missing_admin_profile_by_admin_id_return" +
                    "s_a_not_found_problem_details_response."};

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Admins/UpdateAdminNotFound", "Update admin profile not found", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "UpdateAdminNotFound.feature"
#line hidden

        public UpdateAdminProfileNotFoundFeature(UpdateAdminProfileNotFoundFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Admins/UpdateAdminNotFound/UpdateAdminNotFound.feature.ndjson", 3);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Update admin profile by missing admin id returns not found response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update admin profile not found")]
        [global::Xunit.TraitAttribute("Description", "Update admin profile by missing admin id returns not found response")]
        public async global::System.Threading.Tasks.Task UpdateAdminProfileByMissingAdminIdReturnsNotFoundResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update admin profile by missing admin id returns not found response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "AdminId",
                            "11111111-1111-1111-1111-111111111111"});
                table1.AddRow(new string[] {
                            "FullName",
                            "Missing Update Admin"});
                table1.AddRow(new string[] {
                            "Email",
                            "missing.update.admin@db.com"});
#line 5
    await testRunner.GivenAsync("I have a missing admin update request", ((string)(null)), table1, "Given ");
#line hidden
#line 10
    await testRunner.WhenAsync("I submit the update admin request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "StatusCode",
                            "404"});
                table2.AddRow(new string[] {
                            "Title",
                            "Resource not found."});
                table2.AddRow(new string[] {
                            "Detail",
                            "Resource Admin identified by id 11111111-1111-1111-1111-111111111111 cannot be found in database during action UpdateAdminProfile."});
                table2.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.4"});
                table2.AddRow(new string[] {
                            "Instance",
                            "/admins/11111111-1111-1111-1111-111111111111"});
                table2.AddRow(new string[] {
                            "HasTraceId",
                            "true"});
#line 11
    await testRunner.ThenAsync("the update admin profile request fails with a not found response", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateAdminProfileNotFoundFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateAdminProfileNotFoundFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
