// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateCompanySuccess
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_an_existing_customer_company_returns_a_success_response_with_the_updated_company_payload_fields.")]
    public partial class UpdateCustomerCompanyFeature : object, global::Xunit.IClassFixture<UpdateCustomerCompanyFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_an_existing_customer_company_returns_a_success_response_with_the_updated_company_payload_fields."};

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateCompanySuccess", "Update customer company", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "UpdateCompanySuccess.feature"
#line hidden

        public UpdateCustomerCompanyFeature(UpdateCustomerCompanyFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateCompanySuccess/UpdateCompanySuccess.feature.ndjson", 3);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Update customer company returns updated customer data")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer company")]
        [global::Xunit.TraitAttribute("Description", "Update customer company returns updated customer data")]
        public async global::System.Threading.Tasks.Task Updatecustomercompanyreturnsupdatedcustomerdata()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update customer company returns updated customer data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "ExternalId",
                            "customer-update-company-123456"});
                table1.AddRow(new string[] {
                            "Individual.FirstName",
                            "Company"});
                table1.AddRow(new string[] {
                            "Individual.LastName",
                            "Owner"});
                table1.AddRow(new string[] {
                            "Individual.Email",
                            "company.owner@example.com"});
                table1.AddRow(new string[] {
                            "Individual.Phone",
                            "123456789"});
                table1.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-001"});
                table1.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            "Warsaw"});
                table1.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Marszalkowska"});
                table1.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table1.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "5"});
                table1.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "30-002"});
                table1.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Krakow"});
                table1.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Dluga"});
                table1.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "12"});
                table1.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "7"});
                table1.AddRow(new string[] {
                            "Company.TaxId",
                            "1234567890"});
                table1.AddRow(new string[] {
                            "Company.CompanyName",
                            "Example Company Sp. z o.o."});
                table1.AddRow(new string[] {
                            "Company.BillingAddress.PostalCode",
                            "00-950"});
                table1.AddRow(new string[] {
                            "Company.BillingAddress.City",
                            "Warsaw"});
                table1.AddRow(new string[] {
                            "Company.BillingAddress.Street",
                            "Prosta"});
                table1.AddRow(new string[] {
                            "Company.BillingAddress.BuildingNumber",
                            "20"});
                table1.AddRow(new string[] {
                            "Company.BillingAddress.ApartmentNumber",
                            "15"});
                table1.AddRow(new string[] {
                            "Company.ShippingAddress.PostalCode",
                            "80-001"});
                table1.AddRow(new string[] {
                            "Company.ShippingAddress.City",
                            "Gdansk"});
                table1.AddRow(new string[] {
                            "Company.ShippingAddress.Street",
                            "Portowa"});
                table1.AddRow(new string[] {
                            "Company.ShippingAddress.BuildingNumber",
                            "4A"});
                table1.AddRow(new string[] {
                            "Company.ShippingAddress.ApartmentNumber",
                            "2"});
#line 5
    await testRunner.GivenAsync("a customer with company exists for update company request", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "Company.TaxId",
                            "9876543210"});
                table2.AddRow(new string[] {
                            "Company.CompanyName",
                            "Updated Example Company S.A."});
                table2.AddRow(new string[] {
                            "Company.BillingAddress.PostalCode",
                            "01-234"});
                table2.AddRow(new string[] {
                            "Company.BillingAddress.City",
                            "Poznan"});
                table2.AddRow(new string[] {
                            "Company.BillingAddress.Street",
                            "Nowa"});
                table2.AddRow(new string[] {
                            "Company.BillingAddress.BuildingNumber",
                            "30"});
                table2.AddRow(new string[] {
                            "Company.BillingAddress.ApartmentNumber",
                            "8"});
                table2.AddRow(new string[] {
                            "Company.ShippingAddress.PostalCode",
                            "70-001"});
                table2.AddRow(new string[] {
                            "Company.ShippingAddress.City",
                            "Szczecin"});
                table2.AddRow(new string[] {
                            "Company.ShippingAddress.Street",
                            "Morska"});
                table2.AddRow(new string[] {
                            "Company.ShippingAddress.BuildingNumber",
                            "9B"});
                table2.AddRow(new string[] {
                            "Company.ShippingAddress.ApartmentNumber",
                            "11"});
#line 34
    await testRunner.AndAsync("I have a valid update company request", ((string)(null)), table2, "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("I submit the update company request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table4.AddRow(new string[] {
                            "HasCustomerId",
                            "true"});
                table4.AddRow(new string[] {
                            "ExternalId",
                            "customer-update-company-123456"});
                table4.AddRow(new string[] {
                            "CompanyCount",
                            "1"});
                table4.AddRow(new string[] {
                            "HasCompanyId",
                            "true"});
                table4.AddRow(new string[] {
                            "SameCompanyId",
                            "true"});
                table4.AddRow(new string[] {
                            "Company.TaxId",
                            "9876543210"});
                table4.AddRow(new string[] {
                            "Company.CompanyName",
                            "Updated Example Company S.A."});
                table4.AddRow(new string[] {
                            "Company.BillingAddress.PostalCode",
                            "01-234"});
                table4.AddRow(new string[] {
                            "Company.BillingAddress.City",
                            "Poznan"});
                table4.AddRow(new string[] {
                            "Company.BillingAddress.Street",
                            "Nowa"});
                table4.AddRow(new string[] {
                            "Company.BillingAddress.BuildingNumber",
                            "30"});
                table4.AddRow(new string[] {
                            "Company.BillingAddress.ApartmentNumber",
                            "8"});
                table4.AddRow(new string[] {
                            "Company.ShippingAddress.PostalCode",
                            "70-001"});
                table4.AddRow(new string[] {
                            "Company.ShippingAddress.City",
                            "Szczecin"});
                table4.AddRow(new string[] {
                            "Company.ShippingAddress.Street",
                            "Morska"});
                table4.AddRow(new string[] {
                            "Company.ShippingAddress.BuildingNumber",
                            "9B"});
                table4.AddRow(new string[] {
                            "Company.ShippingAddress.ApartmentNumber",
                            "11"});
#line 49
    await testRunner.ThenAsync("the company is updated successfully", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerCompanyFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerCompanyFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
