// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.CreateCustomerMissingFieldsError
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_creating_a_customer_with_a_payload_missing_required_in" +
        "dividual_json_properties_returns_a_bad_request.")]
    public partial class CreateCustomerProfileDeserializationValidationFeature : object, global::Xunit.IClassFixture<CreateCustomerProfileDeserializationValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_creating_a_customer_with_a_payload_missing_required_in" +
                    "dividual_json_properties_returns_a_bad_request."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/CreateCustomerMissingFieldsError", "Create customer profile deserialization validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateCustomerMissingFieldsError.feature"
#line hidden
        
        public CreateCustomerProfileDeserializationValidationFeature(CreateCustomerProfileDeserializationValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/CreateCustomerMissingFieldsError/CreateCustomerMissingFieldsEr" +
                    "ror.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create customer profile with missing individual email and phone returns deseriali" +
            "zation error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create customer profile deserialization validation")]
        [global::Xunit.TraitAttribute("Description", "Create customer profile with missing individual email and phone returns deseriali" +
            "zation error")]
        public async global::System.Threading.Tasks.Task CreateCustomerProfileWithMissingIndividualEmailAndPhoneReturnsDeserializationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create customer profile with missing individual email and phone returns deseriali" +
                    "zation error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table30.AddRow(new string[] {
                            "ExternalId",
                            "auth-customer-missing-123456"});
                table30.AddRow(new string[] {
                            "Individual.FirstName",
                            "John"});
                table30.AddRow(new string[] {
                            "Individual.LastName",
                            "Doe"});
                table30.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-001"});
                table30.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            "Warsaw"});
                table30.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Main Street"});
                table30.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table30.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "20"});
                table30.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "00-002"});
                table30.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Krakow"});
                table30.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Shipping Street"});
                table30.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "15"});
                table30.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "25"});
#line 5
    await testRunner.GivenAsync("I have a create customer request payload missing the individual email and phone", ((string)(null)), table30, "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("I submit the incomplete create customer request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table31.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table31.AddRow(new string[] {
                            "Title",
                            "Invalid JSON payload."});
                table31.AddRow(new string[] {
                            "Detail",
                            "JSON payload for IndividualDataRequestDto is missing required properties: email, " +
                                "phone."});
                table31.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1"});
                table31.AddRow(new string[] {
                            "MissingProperty",
                            "email"});
                table31.AddRow(new string[] {
                            "MissingProperty",
                            "phone"});
#line 21
    await testRunner.ThenAsync("the create customer response indicates a json deserialization failure", ((string)(null)), table31, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateCustomerProfileDeserializationValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateCustomerProfileDeserializationValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
