// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateIndividualMissingFieldsError
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_customer_individual_data_with_a_payload_missi" +
        "ng_required_individual_json_properties_returns_a_bad_request.")]
    public partial class UpdateCustomerIndividualDataDeserializationValidationFeature : object, global::Xunit.IClassFixture<UpdateCustomerIndividualDataDeserializationValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_customer_individual_data_with_a_payload_missi" +
                    "ng_required_individual_json_properties_returns_a_bad_request."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateIndividualMissingFieldsError", "Update customer individual data deserialization validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateIndividualMissingFieldsError.feature"
#line hidden
        
        public UpdateCustomerIndividualDataDeserializationValidationFeature(UpdateCustomerIndividualDataDeserializationValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateIndividualMissingFieldsError/UpdateIndividualMissingFiel" +
                    "dsError.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update customer individual data with missing individual email and phone returns d" +
            "eserialization error")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer individual data deserialization validation")]
        [global::Xunit.TraitAttribute("Description", "Update customer individual data with missing individual email and phone returns d" +
            "eserialization error")]
        public async global::System.Threading.Tasks.Task UpdateCustomerIndividualDataWithMissingIndividualEmailAndPhoneReturnsDeserializationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update customer individual data with missing individual email and phone returns d" +
                    "eserialization error", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table55.AddRow(new string[] {
                            "ExternalId",
                            "customer-update-individual-missing-123"});
                table55.AddRow(new string[] {
                            "FirstName",
                            "Existing"});
                table55.AddRow(new string[] {
                            "LastName",
                            "Customer"});
                table55.AddRow(new string[] {
                            "Email",
                            "existing.customer@db.com"});
                table55.AddRow(new string[] {
                            "Phone",
                            "111222333"});
                table55.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-001"});
                table55.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table55.AddRow(new string[] {
                            "BillingStreet",
                            "Main Street"});
                table55.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "10"});
                table55.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "20"});
                table55.AddRow(new string[] {
                            "ShippingPostalCode",
                            "00-002"});
                table55.AddRow(new string[] {
                            "ShippingCity",
                            "Krakow"});
                table55.AddRow(new string[] {
                            "ShippingStreet",
                            "Shipping Street"});
                table55.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "15"});
                table55.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "25"});
#line 5
    await testRunner.GivenAsync("a customer exists for update individual missing fields request", ((string)(null)), table55, "Given ");
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table56.AddRow(new string[] {
                            "Individual.FirstName",
                            "Updated"});
                table56.AddRow(new string[] {
                            "Individual.LastName",
                            "Customer"});
                table56.AddRow(new string[] {
                            "Individual.BillingPostalCode",
                            "10-100"});
                table56.AddRow(new string[] {
                            "Individual.BillingCity",
                            "Poznan"});
                table56.AddRow(new string[] {
                            "Individual.BillingStreet",
                            "Update Street"});
                table56.AddRow(new string[] {
                            "Individual.BillingBuildingNumber",
                            "5"});
                table56.AddRow(new string[] {
                            "Individual.BillingApartmentNumber",
                            "11"});
                table56.AddRow(new string[] {
                            "Individual.ShippingPostalCode",
                            "20-200"});
                table56.AddRow(new string[] {
                            "Individual.ShippingCity",
                            "Wroclaw"});
                table56.AddRow(new string[] {
                            "Individual.ShippingStreet",
                            "Delivery Street"});
                table56.AddRow(new string[] {
                            "Individual.ShippingBuildingNumber",
                            "7B"});
                table56.AddRow(new string[] {
                            "Individual.ShippingApartmentNumber",
                            "14"});
#line 22
    await testRunner.AndAsync("I have an update individual request payload missing the individual email and phon" +
                        "e", ((string)(null)), table56, "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("I submit the incomplete update individual request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table57.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table57.AddRow(new string[] {
                            "Title",
                            "Invalid JSON payload."});
                table57.AddRow(new string[] {
                            "Detail",
                            "JSON payload for IndividualDataRequestDto is missing required properties: email, " +
                                "phone."});
                table57.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.1"});
                table57.AddRow(new string[] {
                            "MissingProperty",
                            "email"});
                table57.AddRow(new string[] {
                            "MissingProperty",
                            "phone"});
#line 37
    await testRunner.ThenAsync("the update individual response indicates a json deserialization failure", ((string)(null)), table57, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerIndividualDataDeserializationValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerIndividualDataDeserializationValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
