// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.GetCustomerSuccess
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_getting_an_existing_customer_profile_returns_a_success" +
        "_response_with_the_customer_payload_fields.")]
    public partial class GetCustomerProfileFeature : object, global::Xunit.IClassFixture<GetCustomerProfileFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_getting_an_existing_customer_profile_returns_a_success" +
                    "_response_with_the_customer_payload_fields."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/GetCustomerSuccess", "Get customer profile", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetCustomerSuccess.feature"
#line hidden
        
        public GetCustomerProfileFeature(GetCustomerProfileFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/GetCustomerSuccess/GetCustomerSuccess.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get customer profile by external id returns existing customer data")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Get customer profile")]
        [global::Xunit.TraitAttribute("Description", "Get customer profile by external id returns existing customer data")]
        public async global::System.Threading.Tasks.Task GetCustomerProfileByExternalIdReturnsExistingCustomerData()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get customer profile by external id returns existing customer data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table44.AddRow(new string[] {
                            "ExternalId",
                            "auth-get-customer-123456"});
                table44.AddRow(new string[] {
                            "Individual.FirstName",
                            "Get"});
                table44.AddRow(new string[] {
                            "Individual.LastName",
                            "Customer"});
                table44.AddRow(new string[] {
                            "Individual.Email",
                            "get.customer@db.com"});
                table44.AddRow(new string[] {
                            "Individual.Phone",
                            "123456789"});
                table44.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-001"});
                table44.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            "Warsaw"});
                table44.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Main Street"});
                table44.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table44.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "20"});
                table44.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "00-002"});
                table44.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Krakow"});
                table44.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Shipping Street"});
                table44.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "15"});
                table44.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "25"});
#line 5
    await testRunner.GivenAsync("a customer profile exists for get customer request", ((string)(null)), table44, "Given ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table45.AddRow(new string[] {
                            "ExternalId",
                            "auth-get-customer-123456"});
#line 22
    await testRunner.WhenAsync("I request the customer profile by external id", ((string)(null)), table45, "When ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table46.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table46.AddRow(new string[] {
                            "HasId",
                            "true"});
                table46.AddRow(new string[] {
                            "ExternalId",
                            "auth-get-customer-123456"});
                table46.AddRow(new string[] {
                            "CompaniesCount",
                            "0"});
                table46.AddRow(new string[] {
                            "HasUpdatedAt",
                            "true"});
                table46.AddRow(new string[] {
                            "Individual.FirstName",
                            "Get"});
                table46.AddRow(new string[] {
                            "Individual.LastName",
                            "Customer"});
                table46.AddRow(new string[] {
                            "Individual.Email",
                            "get.customer@db.com"});
                table46.AddRow(new string[] {
                            "Individual.Phone",
                            "123456789"});
                table46.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-001"});
                table46.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            "Warsaw"});
                table46.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Main Street"});
                table46.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table46.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "20"});
                table46.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "00-002"});
                table46.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Krakow"});
                table46.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Shipping Street"});
                table46.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "15"});
                table46.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "25"});
#line 25
    await testRunner.ThenAsync("the customer profile is returned successfully", ((string)(null)), table46, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GetCustomerProfileFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GetCustomerProfileFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
