// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.CreateCustomerValidationError
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_creating_an_individual_customer_profile_with_an_invali" +
        "d_address_returns_a_bad_request_with_validation_errors.")]
    public partial class CreateCustomerProfileValidationFeature : object, global::Xunit.IClassFixture<CreateCustomerProfileValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_creating_an_individual_customer_profile_with_an_invali" +
                    "d_address_returns_a_bad_request_with_validation_errors."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/CreateCustomerValidationError", "Create customer profile validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateCustomerValidationError.feature"
#line hidden
        
        public CreateCustomerProfileValidationFeature(CreateCustomerProfileValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/CreateCustomerValidationError/CreateCustomerValidationError.fe" +
                    "ature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create individual customer profile with invalid billing address returns bad reque" +
            "st")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create customer profile validation")]
        [global::Xunit.TraitAttribute("Description", "Create individual customer profile with invalid billing address returns bad reque" +
            "st")]
        public async global::System.Threading.Tasks.Task CreateIndividualCustomerProfileWithInvalidBillingAddressReturnsBadRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create individual customer profile with invalid billing address returns bad reque" +
                    "st", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table40.AddRow(new string[] {
                            "ExternalId",
                            "auth-customer-654321"});
                table40.AddRow(new string[] {
                            "Individual.FirstName",
                            "John"});
                table40.AddRow(new string[] {
                            "Individual.LastName",
                            "Doe"});
                table40.AddRow(new string[] {
                            "Individual.Email",
                            "john.doe@example.com"});
                table40.AddRow(new string[] {
                            "Individual.Phone",
                            "123456789"});
                table40.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-001"});
                table40.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            ""});
                table40.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Main Street"});
                table40.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table40.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "20"});
                table40.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "00-002"});
                table40.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Krakow"});
                table40.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Shipping Street"});
                table40.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "15"});
                table40.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "25"});
#line 5
    await testRunner.GivenAsync("I have an invalid individual create customer request", ((string)(null)), table40, "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("I submit the create customer request for validation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table41.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table41.AddRow(new string[] {
                            "Message",
                            "City cannot be empty or white space."});
                table41.AddRow(new string[] {
                            "Name",
                            "AddressCityValidationRule"});
                table41.AddRow(new string[] {
                            "Entity",
                            "Address"});
#line 23
    await testRunner.ThenAsync("the customer profile creation fails with a validation error", ((string)(null)), table41, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateCustomerProfileValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateCustomerProfileValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
