// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.AddCompanySuccess
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_adding_a_company_to_an_existing_customer_returns_a_suc" +
        "cess_response_with_the_company_payload_fields.")]
    public partial class AddCustomerCompanyFeature : object, global::Xunit.IClassFixture<AddCustomerCompanyFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_adding_a_company_to_an_existing_customer_returns_a_suc" +
                    "cess_response_with_the_company_payload_fields."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/AddCompanySuccess", "Add customer company", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AddCompanySuccess.feature"
#line hidden
        
        public AddCustomerCompanyFeature(AddCustomerCompanyFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/AddCompanySuccess/AddCompanySuccess.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Add company to customer returns updated customer data")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Add customer company")]
        [global::Xunit.TraitAttribute("Description", "Add company to customer returns updated customer data")]
        public async global::System.Threading.Tasks.Task AddCompanyToCustomerReturnsUpdatedCustomerData()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add company to customer returns updated customer data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table33.AddRow(new string[] {
                            "ExternalId",
                            "customer-company-123456"});
                table33.AddRow(new string[] {
                            "FirstName",
                            "Company"});
                table33.AddRow(new string[] {
                            "LastName",
                            "Client"});
                table33.AddRow(new string[] {
                            "Email",
                            "company.client@db.com"});
                table33.AddRow(new string[] {
                            "Phone",
                            "123456789"});
                table33.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-001"});
                table33.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table33.AddRow(new string[] {
                            "BillingStreet",
                            "Marszalkowska"});
                table33.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "10"});
                table33.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "5"});
                table33.AddRow(new string[] {
                            "ShippingPostalCode",
                            "30-002"});
                table33.AddRow(new string[] {
                            "ShippingCity",
                            "Krakow"});
                table33.AddRow(new string[] {
                            "ShippingStreet",
                            "Dluga"});
                table33.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "12"});
                table33.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "7"});
#line 5
    await testRunner.GivenAsync("a customer exists for add company request", ((string)(null)), table33, "Given ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table34.AddRow(new string[] {
                            "TaxId",
                            "1234567890"});
                table34.AddRow(new string[] {
                            "CompanyName",
                            "Example Company Sp. z o.o."});
                table34.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-950"});
                table34.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table34.AddRow(new string[] {
                            "BillingStreet",
                            "Prosta"});
                table34.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "20"});
                table34.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "15"});
                table34.AddRow(new string[] {
                            "ShippingPostalCode",
                            "80-001"});
                table34.AddRow(new string[] {
                            "ShippingCity",
                            "Gdansk"});
                table34.AddRow(new string[] {
                            "ShippingStreet",
                            "Portowa"});
                table34.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "4A"});
                table34.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "2"});
#line 22
    await testRunner.AndAsync("I have a valid add company request", ((string)(null)), table34, "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("I submit the add company request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table35.AddRow(new string[] {
                            "StatusCode",
                            "200"});
                table35.AddRow(new string[] {
                            "HasCustomerId",
                            "true"});
                table35.AddRow(new string[] {
                            "ExternalId",
                            "customer-company-123456"});
                table35.AddRow(new string[] {
                            "CompanyCount",
                            "1"});
                table35.AddRow(new string[] {
                            "HasCompanyId",
                            "true"});
                table35.AddRow(new string[] {
                            "TaxId",
                            "1234567890"});
                table35.AddRow(new string[] {
                            "CompanyName",
                            "Example Company Sp. z o.o."});
                table35.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-950"});
                table35.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table35.AddRow(new string[] {
                            "BillingStreet",
                            "Prosta"});
                table35.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "20"});
                table35.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "15"});
                table35.AddRow(new string[] {
                            "ShippingPostalCode",
                            "80-001"});
                table35.AddRow(new string[] {
                            "ShippingCity",
                            "Gdansk"});
                table35.AddRow(new string[] {
                            "ShippingStreet",
                            "Portowa"});
                table35.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "4A"});
                table35.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "2"});
#line 37
    await testRunner.ThenAsync("the company is added to the customer successfully", ((string)(null)), table35, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AddCustomerCompanyFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AddCustomerCompanyFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
