// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateIndividualSuccess
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_an_existing_customer_individual_data_returns_a_success" +
        "_response_with_the_updated_individual_payload_fields.")]
    public partial class UpdateCustomerIndividualDataFeature : object, global::Xunit.IClassFixture<UpdateCustomerIndividualDataFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        private global::Reqnroll.ITestRunner testRunner;
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_an_existing_customer_individual_data_returns_a_success" +
                    "_response_with_the_updated_individual_payload_fields."};
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateIndividualSuccess", "Update customer individual data", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
#line 1 "UpdateIndividualSuccess.feature"
#line hidden
        public UpdateCustomerIndividualDataFeature(UpdateCustomerIndividualDataFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateIndividualSuccess/UpdateIndividualSuccess.feature.ndjson", 3);
        }
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        [global::Xunit.SkippableFactAttribute(DisplayName="Update customer individual data returns updated customer profile")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer individual data")]
        [global::Xunit.TraitAttribute("Description", "Update customer individual data returns updated customer profile")]
        public async global::System.Threading.Tasks.Task UpdateCustomerIndividualDataReturnsUpdatedCustomerProfile()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string[] featureTags = UpdateCustomerIndividualDataFeature.featureTags;
            int pickleIndex = 0;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update customer individual data returns updated customer profile", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
#line 4
  this.ScenarioInitialize(scenarioInfo, null);
#line hidden
            await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("a customer exists for update individual request", ((string)(null)), CreateSetupCustomerTable(), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync("I have a valid update individual request", ((string)(null)), CreateUpdateIndividualTable(), "And ");
#line hidden
#line 38
    await testRunner.WhenAsync("I submit the update individual request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the individual data is updated successfully", ((string)(null)), CreateExpectedResultTable(), "Then ");
#line hidden
            await this.ScenarioCleanupAsync();
        }
        private static global::Reqnroll.Table CreateSetupCustomerTable()
        {
            var table = new global::Reqnroll.Table(new string[] { "Field", "Value" });
            table.AddRow(new string[] { "ExternalId", "customer-update-individual-123456" });
            table.AddRow(new string[] { "Individual.FirstName", "Alice" });
            table.AddRow(new string[] { "Individual.LastName", "Client" });
            table.AddRow(new string[] { "Individual.Email", "alice.client@example.com" });
            table.AddRow(new string[] { "Individual.Phone", "123456789" });
            table.AddRow(new string[] { "Individual.BillingAddress.PostalCode", "00-001" });
            table.AddRow(new string[] { "Individual.BillingAddress.City", "Warsaw" });
            table.AddRow(new string[] { "Individual.BillingAddress.Street", "Main Street" });
            table.AddRow(new string[] { "Individual.BillingAddress.BuildingNumber", "10" });
            table.AddRow(new string[] { "Individual.BillingAddress.ApartmentNumber", "20" });
            table.AddRow(new string[] { "Individual.ShippingAddress.PostalCode", "00-002" });
            table.AddRow(new string[] { "Individual.ShippingAddress.City", "Krakow" });
            table.AddRow(new string[] { "Individual.ShippingAddress.Street", "Shipping Street" });
            table.AddRow(new string[] { "Individual.ShippingAddress.BuildingNumber", "15" });
            table.AddRow(new string[] { "Individual.ShippingAddress.ApartmentNumber", "25" });
            return table;
        }
        private static global::Reqnroll.Table CreateUpdateIndividualTable()
        {
            var table = new global::Reqnroll.Table(new string[] { "Field", "Value" });
            table.AddRow(new string[] { "Individual.FirstName", "Alice" });
            table.AddRow(new string[] { "Individual.LastName", "Client" });
            table.AddRow(new string[] { "Individual.Email", "alice.updated@example.com" });
            table.AddRow(new string[] { "Individual.Phone", "987654321" });
            table.AddRow(new string[] { "Individual.BillingAddress.PostalCode", "00-950" });
            table.AddRow(new string[] { "Individual.BillingAddress.City", "Warsaw" });
            table.AddRow(new string[] { "Individual.BillingAddress.Street", "Prosta" });
            table.AddRow(new string[] { "Individual.BillingAddress.BuildingNumber", "20" });
            table.AddRow(new string[] { "Individual.BillingAddress.ApartmentNumber", "15" });
            table.AddRow(new string[] { "Individual.ShippingAddress.PostalCode", "80-001" });
            table.AddRow(new string[] { "Individual.ShippingAddress.City", "Gdansk" });
            table.AddRow(new string[] { "Individual.ShippingAddress.Street", "Portowa" });
            table.AddRow(new string[] { "Individual.ShippingAddress.BuildingNumber", "4A" });
            table.AddRow(new string[] { "Individual.ShippingAddress.ApartmentNumber", "2" });
            return table;
        }
        private static global::Reqnroll.Table CreateExpectedResultTable()
        {
            var table = new global::Reqnroll.Table(new string[] { "Field", "Value" });
            table.AddRow(new string[] { "StatusCode", "200" });
            table.AddRow(new string[] { "HasCustomerId", "true" });
            table.AddRow(new string[] { "ExternalId", "customer-update-individual-123456" });
            table.AddRow(new string[] { "CompanyCount", "0" });
            table.AddRow(new string[] { "Individual.FirstName", "Alice" });
            table.AddRow(new string[] { "Individual.LastName", "Client" });
            table.AddRow(new string[] { "Individual.Email", "alice.updated@example.com" });
            table.AddRow(new string[] { "Individual.Phone", "987654321" });
            table.AddRow(new string[] { "Individual.BillingAddress.PostalCode", "00-950" });
            table.AddRow(new string[] { "Individual.BillingAddress.City", "Warsaw" });
            table.AddRow(new string[] { "Individual.BillingAddress.Street", "Prosta" });
            table.AddRow(new string[] { "Individual.BillingAddress.BuildingNumber", "20" });
            table.AddRow(new string[] { "Individual.BillingAddress.ApartmentNumber", "15" });
            table.AddRow(new string[] { "Individual.ShippingAddress.PostalCode", "80-001" });
            table.AddRow(new string[] { "Individual.ShippingAddress.City", "Gdansk" });
            table.AddRow(new string[] { "Individual.ShippingAddress.Street", "Portowa" });
            table.AddRow(new string[] { "Individual.ShippingAddress.BuildingNumber", "4A" });
            table.AddRow(new string[] { "Individual.ShippingAddress.ApartmentNumber", "2" });
            return table;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerIndividualDataFeature.FeatureSetupAsync();
            }
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerIndividualDataFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
