// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.AddCompanyValidationError
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_adding_a_company_with_invalid_company_data_to_an_existing_customer_returns_a_bad_request_with_validation_errors.")]
    public partial class AddCustomerCompanyValidationFeature : object, global::Xunit.IClassFixture<AddCustomerCompanyValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = new string[] {
                "allure.description:Ensures_adding_a_company_with_invalid_company_data_to_an_existing_customer_returns_a_bad_request_with_validation_errors."};

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/AddCompanyValidationError", "Add customer company validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "AddCompanyValidationError.feature"
#line hidden

        public AddCustomerCompanyValidationFeature(AddCustomerCompanyValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/AddCompanyValidationError/AddCompanyValidationError.feature.ndjson", 3);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Add company with invalid tax id returns bad request")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Add customer company validation")]
        [global::Xunit.TraitAttribute("Description", "Add company with invalid tax id returns bad request")]
        public async global::System.Threading.Tasks.Task AddCompanyWithInvalidTaxIdReturnsBadRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add company with invalid tax id returns bad request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table25.AddRow(new string[] {
                            "ExternalId",
                            "customer-company-validation-123"});
                table25.AddRow(new string[] {
                            "FirstName",
                            "Company"});
                table25.AddRow(new string[] {
                            "LastName",
                            "Validation"});
                table25.AddRow(new string[] {
                            "Email",
                            "company.validation@db.com"});
                table25.AddRow(new string[] {
                            "Phone",
                            "123456789"});
                table25.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-001"});
                table25.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table25.AddRow(new string[] {
                            "BillingStreet",
                            "Marszalkowska"});
                table25.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "10"});
                table25.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "5"});
                table25.AddRow(new string[] {
                            "ShippingPostalCode",
                            "30-002"});
                table25.AddRow(new string[] {
                            "ShippingCity",
                            "Krakow"});
                table25.AddRow(new string[] {
                            "ShippingStreet",
                            "Dluga"});
                table25.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "12"});
                table25.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "7"});
#line 5
    await testRunner.GivenAsync("a customer exists for add company validation request", ((string)(null)), table25, "Given ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table26.AddRow(new string[] {
                            "TaxId",
                            "invalid-tax-id"});
                table26.AddRow(new string[] {
                            "CompanyName",
                            "Invalid Tax Company Sp. z o.o."});
                table26.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-950"});
                table26.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table26.AddRow(new string[] {
                            "BillingStreet",
                            "Prosta"});
                table26.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "20"});
                table26.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "15"});
                table26.AddRow(new string[] {
                            "ShippingPostalCode",
                            "80-001"});
                table26.AddRow(new string[] {
                            "ShippingCity",
                            "Gdansk"});
                table26.AddRow(new string[] {
                            "ShippingStreet",
                            "Portowa"});
                table26.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "4A"});
                table26.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "2"});
#line 22
    await testRunner.AndAsync("I have an invalid add company request", ((string)(null)), table26, "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("I submit the add company request for validation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table27.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table27.AddRow(new string[] {
                            "Message",
                            "Tax Id must be a valid Polish NIP containing exactly 10 digits."});
                table27.AddRow(new string[] {
                            "Name",
                            "CompanyDataTaxIdValidationRule"});
                table27.AddRow(new string[] {
                            "Entity",
                            "CompanyData"});
#line 37
    await testRunner.ThenAsync("adding the company fails with a validation error", ((string)(null)), table27, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AddCustomerCompanyValidationFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AddCustomerCompanyValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
