// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.CreateCustomerConflictError
{


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_creating_a_duplicate_customer_profile_returns_a_conflict" +
        "_response.")]
    public partial class CreateCustomerProfileConflictFeature : object, global::Xunit.IClassFixture<CreateCustomerProfileConflictFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {

        private global::Reqnroll.ITestRunner testRunner;

        private static string[] featureTags = new string[] {
                "allure.description:Ensures_creating_a_duplicate_customer_profile_returns_a_conflict" +
                    "_response."};

        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/CreateCustomerConflictError", "Create customer profile conflict", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());

        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "CreateCustomerConflictError.feature"
#line hidden

        public CreateCustomerProfileConflictFeature(CreateCustomerProfileConflictFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }

        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }

        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }

        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null)
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null)
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }

        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }

        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }

        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }

        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/CreateCustomerConflictError/CreateCustomerConflictError.feature.ndjson", 3);
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }

        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }

        [global::Xunit.SkippableFactAttribute(DisplayName="Create duplicate individual customer profile returns conflict response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create customer profile conflict")]
        [global::Xunit.TraitAttribute("Description", "Create duplicate individual customer profile returns conflict response")]
        public async global::System.Threading.Tasks.Task CreateDuplicateIndividualCustomerProfileReturnsConflictResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create duplicate individual customer profile returns conflict response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] { "ExternalId", "auth-customer-conflict-123456" });
                table1.AddRow(new string[] { "Individual.FirstName", "Jane" });
                table1.AddRow(new string[] { "Individual.LastName", "Duplicate" });
                table1.AddRow(new string[] { "Individual.Email", "jane.duplicate@example.com" });
                table1.AddRow(new string[] { "Individual.Phone", "987654321" });
                table1.AddRow(new string[] { "Individual.BillingAddress.PostalCode", "01-001" });
                table1.AddRow(new string[] { "Individual.BillingAddress.City", "Warsaw" });
                table1.AddRow(new string[] { "Individual.BillingAddress.Street", "Conflict Street" });
                table1.AddRow(new string[] { "Individual.BillingAddress.BuildingNumber", "11" });
                table1.AddRow(new string[] { "Individual.BillingAddress.ApartmentNumber", "21" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.PostalCode", "01-002" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.City", "Krakow" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.Street", "Duplicate Avenue" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.BuildingNumber", "16" });
                table1.AddRow(new string[] { "Individual.ShippingAddress.ApartmentNumber", "26" });
#line 5
    await testRunner.GivenAsync("I have a valid create individual customer request payload", ((string)(null)), table1, "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("I submit the same create customer request twice", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] { "StatusCode", "409" });
                table2.AddRow(new string[] { "Status", "409" });
                table2.AddRow(new string[] { "Title", "Conflict." });
                table2.AddRow(new string[] { "Type", "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.8" });
                table2.AddRow(new string[] { "Instance", "/customers" });
                table2.AddRow(new string[] { "DetailContains", "Resource Customer identified by id auth-customer-conflict-123456 already exists in db. Error in action CreateCustomer." });
                table2.AddRow(new string[] { "HasTraceId", "true" });
#line 23
    await testRunner.ThenAsync("the customer profile creation fails with a conflict error", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateCustomerProfileConflictFeature.FeatureSetupAsync();
            }

            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateCustomerProfileConflictFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
