// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateCompanyNotFound
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_a_company_that_does_not_exist_for_an_existing" +
        "_customer_returns_a_not_found_problem_details_response.")]
    public partial class UpdateCompanyNotFoundFeature : object, global::Xunit.IClassFixture<UpdateCompanyNotFoundFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_a_company_that_does_not_exist_for_an_existing" +
                    "_customer_returns_a_not_found_problem_details_response."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateCompanyNotFound", "Update company not found", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateCompanyNotFound.feature"
#line hidden
        
        public UpdateCompanyNotFoundFeature(UpdateCompanyNotFoundFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateCompanyNotFound/UpdateCompanyNotFound.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update missing company for existing customer returns not found response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update company not found")]
        [global::Xunit.TraitAttribute("Description", "Update missing company for existing customer returns not found response")]
        public async global::System.Threading.Tasks.Task UpdateMissingCompanyForExistingCustomerReturnsNotFoundResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update missing company for existing customer returns not found response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table61.AddRow(new string[] {
                            "ExternalId",
                            "auth-customer-update-company-not-found-123"});
                table61.AddRow(new string[] {
                            "Individual.FirstName",
                            "Update"});
                table61.AddRow(new string[] {
                            "Individual.LastName",
                            "CompanyNotFound"});
                table61.AddRow(new string[] {
                            "Individual.Email",
                            "update.company.notfound@example.com"});
                table61.AddRow(new string[] {
                            "Individual.Phone",
                            "111222333"});
                table61.AddRow(new string[] {
                            "Individual.BillingAddress.PostalCode",
                            "00-950"});
                table61.AddRow(new string[] {
                            "Individual.BillingAddress.City",
                            "Warsaw"});
                table61.AddRow(new string[] {
                            "Individual.BillingAddress.Street",
                            "Existing Customer Street"});
                table61.AddRow(new string[] {
                            "Individual.BillingAddress.BuildingNumber",
                            "10"});
                table61.AddRow(new string[] {
                            "Individual.BillingAddress.ApartmentNumber",
                            "5"});
                table61.AddRow(new string[] {
                            "Individual.ShippingAddress.PostalCode",
                            "80-001"});
                table61.AddRow(new string[] {
                            "Individual.ShippingAddress.City",
                            "Gdansk"});
                table61.AddRow(new string[] {
                            "Individual.ShippingAddress.Street",
                            "Existing Customer Shipping"});
                table61.AddRow(new string[] {
                            "Individual.ShippingAddress.BuildingNumber",
                            "12"});
                table61.AddRow(new string[] {
                            "Individual.ShippingAddress.ApartmentNumber",
                            "7"});
                table61.AddRow(new string[] {
                            "ExistingCompany.TaxId",
                            "1234509876"});
                table61.AddRow(new string[] {
                            "ExistingCompany.CompanyName",
                            "Existing Company Sp. z o.o."});
                table61.AddRow(new string[] {
                            "ExistingCompany.BillingAddress.PostalCode",
                            "30-300"});
                table61.AddRow(new string[] {
                            "ExistingCompany.BillingAddress.City",
                            "Poznan"});
                table61.AddRow(new string[] {
                            "ExistingCompany.BillingAddress.Street",
                            "Business"});
                table61.AddRow(new string[] {
                            "ExistingCompany.BillingAddress.BuildingNumber",
                            "3"});
                table61.AddRow(new string[] {
                            "ExistingCompany.BillingAddress.ApartmentNumber",
                            "15"});
                table61.AddRow(new string[] {
                            "ExistingCompany.ShippingAddress.PostalCode",
                            "40-400"});
                table61.AddRow(new string[] {
                            "ExistingCompany.ShippingAddress.City",
                            "Lodz"});
                table61.AddRow(new string[] {
                            "ExistingCompany.ShippingAddress.Street",
                            "Industry"});
                table61.AddRow(new string[] {
                            "ExistingCompany.ShippingAddress.BuildingNumber",
                            "4"});
                table61.AddRow(new string[] {
                            "ExistingCompany.ShippingAddress.ApartmentNumber",
                            "16"});
#line 5
    await testRunner.GivenAsync("a customer with a company exists for update company not found request", ((string)(null)), table61, "Given ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table62.AddRow(new string[] {
                            "CompanyId",
                            "44444444-4444-4444-4444-444444444444"});
                table62.AddRow(new string[] {
                            "TaxId",
                            "9988776655"});
                table62.AddRow(new string[] {
                            "CompanyName",
                            "Missing Company Updated Sp. z o.o."});
                table62.AddRow(new string[] {
                            "BillingAddress.PostalCode",
                            "50-500"});
                table62.AddRow(new string[] {
                            "BillingAddress.City",
                            "Wroclaw"});
                table62.AddRow(new string[] {
                            "BillingAddress.Street",
                            "Update Billing"});
                table62.AddRow(new string[] {
                            "BillingAddress.BuildingNumber",
                            "50"});
                table62.AddRow(new string[] {
                            "BillingAddress.ApartmentNumber",
                            "55"});
                table62.AddRow(new string[] {
                            "ShippingAddress.PostalCode",
                            "60-600"});
                table62.AddRow(new string[] {
                            "ShippingAddress.City",
                            "Szczecin"});
                table62.AddRow(new string[] {
                            "ShippingAddress.Street",
                            "Update Shipping"});
                table62.AddRow(new string[] {
                            "ShippingAddress.BuildingNumber",
                            "60"});
                table62.AddRow(new string[] {
                            "ShippingAddress.ApartmentNumber",
                            "66"});
#line 34
    await testRunner.AndAsync("I have an update missing company request", ((string)(null)), table62, "And ");
#line hidden
#line 49
    await testRunner.WhenAsync("I submit the update missing company request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table63.AddRow(new string[] {
                            "StatusCode",
                            "404"});
                table63.AddRow(new string[] {
                            "Title",
                            "Resource not found."});
                table63.AddRow(new string[] {
                            "Detail",
                            "Resource CompanyData identified by id {CompanyId} cannot be found in database dur" +
                                "ing action LoadCompany."});
                table63.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.4"});
                table63.AddRow(new string[] {
                            "InstanceTemplate",
                            "/customers/{CustomerId}/companies/{CompanyId}"});
                table63.AddRow(new string[] {
                            "HasTraceId",
                            "true"});
#line 50
    await testRunner.ThenAsync("the update company request fails with a not found response", ((string)(null)), table63, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCompanyNotFoundFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCompanyNotFoundFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
