// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.AddCompanyNotFound
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_adding_a_company_to_a_missing_customer_by_customer_id_" +
        "returns_a_not_found_problem_details_response.")]
    public partial class AddCompanyNotFoundFeature : object, global::Xunit.IClassFixture<AddCompanyNotFoundFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_adding_a_company_to_a_missing_customer_by_customer_id_" +
                    "returns_a_not_found_problem_details_response."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/AddCompanyNotFound", "Add company not found", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AddCompanyNotFound.feature"
#line hidden
        
        public AddCompanyNotFoundFeature(AddCompanyNotFoundFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/AddCompanyNotFound/AddCompanyNotFound.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Add company by missing customer id returns not found response")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Add company not found")]
        [global::Xunit.TraitAttribute("Description", "Add company by missing customer id returns not found response")]
        public async global::System.Threading.Tasks.Task AddCompanyByMissingCustomerIdReturnsNotFoundResponse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add company by missing customer id returns not found response", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table28.AddRow(new string[] {
                            "CustomerId",
                            "22222222-2222-2222-2222-222222222222"});
                table28.AddRow(new string[] {
                            "TaxId",
                            "1234567890"});
                table28.AddRow(new string[] {
                            "CompanyName",
                            "Missing Customer Company Sp. z o.o."});
                table28.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-950"});
                table28.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table28.AddRow(new string[] {
                            "BillingStreet",
                            "Prosta"});
                table28.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "20"});
                table28.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "15"});
                table28.AddRow(new string[] {
                            "ShippingPostalCode",
                            "80-001"});
                table28.AddRow(new string[] {
                            "ShippingCity",
                            "Gdansk"});
                table28.AddRow(new string[] {
                            "ShippingStreet",
                            "Portowa"});
                table28.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "4A"});
                table28.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "2"});
#line 5
    await testRunner.GivenAsync("I have a missing customer add company request", ((string)(null)), table28, "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("I submit the missing customer add company request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table29.AddRow(new string[] {
                            "StatusCode",
                            "404"});
                table29.AddRow(new string[] {
                            "Title",
                            "Resource not found."});
                table29.AddRow(new string[] {
                            "Detail",
                            "Resource Customer identified by id 22222222-2222-2222-2222-222222222222 cannot be" +
                                " found in database during action AddCompany."});
                table29.AddRow(new string[] {
                            "Type",
                            "https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.4"});
                table29.AddRow(new string[] {
                            "Instance",
                            "/customers/22222222-2222-2222-2222-222222222222/companies"});
                table29.AddRow(new string[] {
                            "HasTraceId",
                            "true"});
#line 21
    await testRunner.ThenAsync("the add company request fails with a not found response", ((string)(null)), table29, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AddCompanyNotFoundFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AddCompanyNotFoundFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
