// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ECommerceStoreUsers.AcceptanceTests.Features.Customers.UpdateIndividualValidationError
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.description:Ensures_updating_existing_customer_individual_data_with_invali" +
        "d_contact_values_returns_a_bad_request_with_validation_errors.")]
    public partial class UpdateCustomerIndividualDataValidationFeature : object, global::Xunit.IClassFixture<UpdateCustomerIndividualDataValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.description:Ensures_updating_existing_customer_individual_data_with_invali" +
                    "d_contact_values_returns_a_bad_request_with_validation_errors."};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Customers/UpdateIndividualValidationError", "Update customer individual data validation", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UpdateIndividualValidationError.feature"
#line hidden
        
        public UpdateCustomerIndividualDataValidationFeature(UpdateCustomerIndividualDataValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Customers/UpdateIndividualValidationError/UpdateIndividualValidationErro" +
                    "r.feature.ndjson", 3);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update existing customer individual data with invalid contact values returns bad " +
            "request")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Update customer individual data validation")]
        [global::Xunit.TraitAttribute("Description", "Update existing customer individual data with invalid contact values returns bad " +
            "request")]
        public async global::System.Threading.Tasks.Task UpdateExistingCustomerIndividualDataWithInvalidContactValuesReturnsBadRequest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update existing customer individual data with invalid contact values returns bad " +
                    "request", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table63.AddRow(new string[] {
                            "ExternalId",
                            "customer-update-individual-validation"});
                table63.AddRow(new string[] {
                            "FirstName",
                            "Update"});
                table63.AddRow(new string[] {
                            "LastName",
                            "Individual"});
                table63.AddRow(new string[] {
                            "Email",
                            "update.individual@db.com"});
                table63.AddRow(new string[] {
                            "Phone",
                            "123456789"});
                table63.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-001"});
                table63.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table63.AddRow(new string[] {
                            "BillingStreet",
                            "Marszalkowska"});
                table63.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "10"});
                table63.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "5"});
                table63.AddRow(new string[] {
                            "ShippingPostalCode",
                            "30-002"});
                table63.AddRow(new string[] {
                            "ShippingCity",
                            "Krakow"});
                table63.AddRow(new string[] {
                            "ShippingStreet",
                            "Dluga"});
                table63.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "12"});
                table63.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "7"});
#line 5
    await testRunner.GivenAsync("a customer exists for update individual validation request", ((string)(null)), table63, "Given ");
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table64.AddRow(new string[] {
                            "FirstName",
                            "Updated"});
                table64.AddRow(new string[] {
                            "LastName",
                            "Customer"});
                table64.AddRow(new string[] {
                            "Email",
                            "invalid-email"});
                table64.AddRow(new string[] {
                            "Phone",
                            "12345ab"});
                table64.AddRow(new string[] {
                            "BillingPostalCode",
                            "00-950"});
                table64.AddRow(new string[] {
                            "BillingCity",
                            "Warsaw"});
                table64.AddRow(new string[] {
                            "BillingStreet",
                            "Prosta"});
                table64.AddRow(new string[] {
                            "BillingBuildingNumber",
                            "20"});
                table64.AddRow(new string[] {
                            "BillingApartmentNumber",
                            "15"});
                table64.AddRow(new string[] {
                            "ShippingPostalCode",
                            "80-001"});
                table64.AddRow(new string[] {
                            "ShippingCity",
                            "Gdansk"});
                table64.AddRow(new string[] {
                            "ShippingStreet",
                            "Portowa"});
                table64.AddRow(new string[] {
                            "ShippingBuildingNumber",
                            "4A"});
                table64.AddRow(new string[] {
                            "ShippingApartmentNumber",
                            "2"});
#line 22
    await testRunner.AndAsync("I have an invalid update individual request", ((string)(null)), table64, "And ");
#line hidden
#line 38
    await testRunner.WhenAsync("I submit the update individual request for validation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table65.AddRow(new string[] {
                            "StatusCode",
                            "400"});
                table65.AddRow(new string[] {
                            "EmailMessage",
                            "Email must be a valid format (address@domain.something)."});
                table65.AddRow(new string[] {
                            "EmailName",
                            "IndividualDataEmailValidationRule"});
                table65.AddRow(new string[] {
                            "EmailEntity",
                            "IndividualData"});
                table65.AddRow(new string[] {
                            "PhoneMessage",
                            "Phone must contain only digits and be between 7 and 10 characters long."});
                table65.AddRow(new string[] {
                            "PhoneName",
                            "IndividualDataPhoneValidationRule"});
                table65.AddRow(new string[] {
                            "PhoneEntity",
                            "IndividualData"});
#line 39
    await testRunner.ThenAsync("updating the individual data fails with validation errors", ((string)(null)), table65, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UpdateCustomerIndividualDataValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UpdateCustomerIndividualDataValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
